Plugin:
  # Enter here all commands prisoners are allowed to use (with '/')
  # Otherwise all commands are disabled
  Whitelisted-Commands:
    - /login
    - /logout

  # You can change this value by your favorite language (corresponding to the <lang>.yml on the plugin directory)
  Language: en

Prisoners:
  # Allow prisoners to speak and ear
  Speak: false
  Ear: false
  
  # Allow admin to use all commands, even if there are prisoners
  Admin-cmds: false
    
Jails:
  # All default values for jails can be modified on jails.yml or with /jw-config <jail_name>
  # Default value for number of blocks prisoner have to break (when not defined with /jw-config)
  Blocks: 500
  
  # Default value for number max of sand blocks can spawn on jails
  MaxSand: 5
  
  # Default value for speed-spawn for blocks on jails (seconds)
  Speed: 2
  
  Type: SAND